CREATE DATABASE EXERCISE2;
USE EXERCISE2;

CREATE TABLE SimpleTable(
column1 NCHAR(10),
column2 NCHAR(10));

--DROP TABLE SimpleTable;
--USE MASTER; -- To leave database EXERCISE2
--DROP DATABASE EXERCISE2;
