version: "3.8"

services:
  database:
    container_name: mssql-exercices
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - ./database.env
    ports:
      - 1433:1433
    volumes:
      - mssql-exercices:/var/opt/mssql

volumes:
  mssql-exercices:
